spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=bookstore
spring.datasource.password=bookstore

bookstore.recommendation.collaborative-weight=0.65

logging.file.name=logs/bookstore-techui.log
logging.file.error.name=logs/bookstore-errors.log

spring.data.redis.host=localhost
spring.data.redis.port=6379
