spring.application.name=bookstore-business-logic

spring.profiles.default=postgres

logging.level.root=INFO
logging.level.ru.bookstore=DEBUG
logging.file.name=logs/bookstore.log
logging.file.error.name=logs/bookstore-errors.log

spring.data.redis.host=localhost
spring.data.redis.port=6379
